import ray
from ray.rllib.core.rl_module import RLModule
from pathlib import Path
import shutil

from sim_env.parameters import Config, PI
from sim_env.parking_env import Parking
from sim_env.main import compute_action
from training.training import train_and_evaluate


TEST_SCENARIOS = [
    # perpendicular parking type4
    {
        'config':
            Config(car_length=4.0, car_width=2.0,
                   wheel_length=0.75, wheel_width=0.35,
                   parking_length=6.0, parking_width=4.0,
                   max_distance=25.0, max_steps=80,
                   acceleration_limit=1.0, steering_limit=PI / 4, velocity_limit=2.77778,
                   max_angle_error=PI / 4.5, center_threshold=0.5, penalty_ratio={'angle': 0.25, 'velocity': 0.25},
                   reward_type='type4', state_type='type4',
                   side=1, car_loc_randomize_range=(-5, 5), initial_distance_range=(7.5, 15.0)
                   ),
        'num_train': 3,
        'parking_type': 'perpendicular',
    },
    # parallel parking type4
    {
        'config':
            Config(car_length=4.0, car_width=2.0,
                   wheel_length=0.75, wheel_width=0.35,
                   parking_length=6.0, parking_width=4.0,
                   max_distance=25.0, max_steps=80,
                   acceleration_limit=1.0, steering_limit=PI/4, velocity_limit=2.77778,
                   max_angle_error=PI/6, center_threshold=0.5, penalty_ratio={'angle': 0.25, 'velocity': 0.25},
                   reward_type='type4', state_type='type4',
                   side=1, car_loc_randomize_range=(6.0, 7.0), initial_distance_range=(5.0, 7.0),
                   heading_angle_range={"parallel": {1: (PI/6, PI/4)}}
                   ),
        'num_train': 3,
        'parking_type': 'parallel',
    }
]


def test_training_and_evaluation():

    checkpoint_paths = []
    created_paths = []

    ray.init()

    try:
        for scenario in TEST_SCENARIOS:
            training_result_path, checkpoint_path = train_and_evaluate(**scenario)
            training_result_dir = Path(training_result_path)
            checkpoint_path = Path(checkpoint_path)

            checkpoint_paths.append(checkpoint_path)

            created_paths.extend([training_result_dir, checkpoint_path])

        for scenario, checkpoint_path in zip(TEST_SCENARIOS, checkpoint_paths):

            config = scenario["config"]

            env_config = {
                "render_mode": "no_render",
                "action_type": "continuous",
                "parking_type": scenario["parking_type"],
                "training_mode": "off",
                'config': config}

            env = Parking(env_config)
            try:
                if not checkpoint_path.exists():
                    raise FileNotFoundError(f"Checkpoint directory does not exist: {checkpoint_path}")

                # Load RLModule from checkpoint
                rl_module = RLModule.from_checkpoint(
                    checkpoint_path / "learner_group" / "learner" / "rl_module" / "default_policy")

                action_dist_cls = rl_module.get_inference_action_dist_cls()

                for i in range(3):
                    episode_reward = 0
                    terminated = truncated = False
                    obs, info = env.reset()

                    while not terminated and not truncated:
                        action = compute_action(rl_module, action_dist_cls, obs)
                        obs, reward, terminated, truncated, info = env.step(action)
                        episode_reward += reward
                        print(f'{i}: {episode_reward}')

            finally:
                env.close()

    finally:
        ray.shutdown()

        # Delete all directories generated by this smoke test.
        for path in created_paths:
            if path.exists():
                shutil.rmtree(path)
